### ISSUE TITLE
Unable to open Output file.

### ISSUE THREAD

**Issue by swathir01** [mmathew23/LAG-Pytorch#3]
How to open the **samples.pt** file to view the output?

**Comment by mmathew23** [comment]
pt files are a naming convention to indicate that the file is used for pytorch. The sample.pt file saves the real images so that if you want to pick up training from a checkpoint, it continues to compare against the same samples it initially did. If you wanted, you could load this file into pytorch, which I do in model.load, and generate the image which I do in model.gen_samples. 

The code also logs samples using tensorboard throughout training if you want to view samples. `tensorboard --logdir LOGDIR` should do the trick.
